import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import {
  Box,
  Card,
  CardContent,
  TextField,
  Button,
  Typography,
  Alert,
  CircularProgress,
  InputAdornment,
  IconButton,
  useTheme,
} from "@mui/material";
import {
  Visibility,
  VisibilityOff,
  Person as PersonIcon,
  Lock as LockIcon,
  Email as EmailIcon,
} from "@mui/icons-material";
import { useForm } from "react-hook-form";
import api from "../../lib/api";

/**
 * Define API Error structure to avoid 'any' type
 */
interface ApiError {
  response?: {
    data?: {
      message?: string;
    };
  };
}

type RegisterFormValues = {
  username: string;
  password: string;
  confirmPassword: string;
};

const Register = () => {
  const theme = useTheme();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  // Extract token and email from the URL generated by HR
  const token = searchParams.get("token");
  const email = searchParams.get("email");
  const missingToken = !token;

  // UI States
  const [showPassword, setShowPassword] = useState(false);
  const [checkingToken, setCheckingToken] = useState<boolean>(!missingToken);
  const [tokenError, setTokenError] = useState<string | null>(
    missingToken ? "Missing registration token." : null,
  );

  const {
    register,
    handleSubmit,
    getValues,
    formState: { errors, isSubmitting },
  } = useForm<RegisterFormValues>();

  /**
   * Validate the invitation token on component mount
   */
  useEffect(() => {
    if (missingToken || !token) return;

    let active = true;
    api
      .get(`/auth/registration/${token}`)
      .then(() => {
        if (active) setTokenError(null);
      })
      .catch((err: unknown) => {
        if (!active) return;

        const apiError = err as ApiError;
        const message = apiError.response?.data?.message;

        if (message === "Invalid token") {
          setTokenError("Invalid invitation link.");
        } else if (message === "Token already used") {
          setTokenError("This invitation link has already been used.");
        } else if (message === "Token expired") {
          setTokenError("This invitation link has expired.");
        } else {
          setTokenError("Unable to validate invitation link.");
        }
      })
      .finally(() => {
        if (active) setCheckingToken(false);
      });

    return () => {
      active = false;
    };
  }, [token, missingToken]);

  /**
   * Handle registration form submission
   */
  const onSubmit = async (data: RegisterFormValues) => {
    if (!token || !email) return;

    try {
      await api.post("/auth/register", {
        token,
        email,
        username: data.username,
        password: data.password,
      });
      // Redirect to login page upon successful registration
      navigate("/login");
    } catch (err: unknown) {
      const apiError = err as ApiError;
      const message = apiError.response?.data?.message;

      if (message === "Email already registered") {
        setTokenError("This email has already been registered.");
      } else {
        setTokenError("Registration failed. Please try again.");
      }
    }
  };

  // Loading state during initial token validation
  if (checkingToken) {
    return (
      <Box
        sx={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background: `linear-gradient(135deg, ${theme.palette.primary.dark} 0%, ${theme.palette.primary.main} 50%, ${theme.palette.secondary.main} 100%)`,
        }}
      >
        <CircularProgress sx={{ color: "white" }} />
        <Typography sx={{ mt: 2, color: "white", fontWeight: 500 }}>
          Validating invitation...
        </Typography>
      </Box>
    );
  }

  return (
    <Box
      sx={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: `linear-gradient(135deg, ${theme.palette.primary.dark} 0%, ${theme.palette.primary.main} 50%, ${theme.palette.secondary.main} 100%)`,
        p: 2,
      }}
    >
      <Card
        sx={{
          maxWidth: 480,
          width: "100%",
          boxShadow: theme.shadows[10],
          borderRadius: 3,
        }}
      >
        <CardContent sx={{ p: 4 }}>
          {/* Brand Logo Section */}
          <Box sx={{ textAlign: "center", mb: 4 }}>
            <Box
              sx={{
                width: 60,
                height: 60,
                borderRadius: 2,
                background: `linear-gradient(135deg, ${theme.palette.primary.main}, ${theme.palette.primary.dark})`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                mx: "auto",
                mb: 2,
                boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
              }}
            >
              <Typography variant="h4" sx={{ color: "white", fontWeight: 800 }}>
                E
              </Typography>
            </Box>
            <Typography variant="h4" sx={{ fontWeight: 700, mb: 0.5 }}>
              Create Account
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Enter your details to complete registration
            </Typography>
          </Box>

          {/* Error display */}
          {tokenError && (
            <Alert severity="error" sx={{ mb: 3, borderRadius: 2 }}>
              {tokenError}
            </Alert>
          )}

          {/* Form Section */}
          <Box component="form" onSubmit={handleSubmit(onSubmit)} noValidate>
            <TextField
              fullWidth
              label="Email Address"
              value={email ?? ""}
              margin="normal"
              disabled
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <EmailIcon fontSize="small" color="action" />
                  </InputAdornment>
                ),
              }}
              helperText="Pre-filled from your invitation"
            />

            <TextField
              fullWidth
              label="Username"
              placeholder="Choose a username"
              margin="normal"
              disabled={!!tokenError}
              {...register("username", {
                required: "Username is required",
                minLength: { value: 3, message: "At least 3 characters" },
              })}
              error={!!errors.username}
              helperText={errors.username?.message}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <PersonIcon fontSize="small" color="action" />
                  </InputAdornment>
                ),
              }}
            />

            <TextField
              fullWidth
              label="Password"
              type={showPassword ? "text" : "password"}
              placeholder="Create a password"
              margin="normal"
              disabled={!!tokenError}
              {...register("password", {
                required: "Password is required",
                minLength: { value: 8, message: "At least 8 characters" },
              })}
              error={!!errors.password}
              helperText={errors.password?.message || "Minimum 8 characters"}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <LockIcon fontSize="small" color="action" />
                  </InputAdornment>
                ),
                endAdornment: (
                  <InputAdornment position="end">
                    <IconButton
                      onClick={() => setShowPassword(!showPassword)}
                      edge="end"
                    >
                      {showPassword ? <VisibilityOff /> : <Visibility />}
                    </IconButton>
                  </InputAdornment>
                ),
              }}
            />

            <TextField
              fullWidth
              label="Confirm Password"
              type={showPassword ? "text" : "password"}
              placeholder="Repeat your password"
              margin="normal"
              disabled={!!tokenError}
              {...register("confirmPassword", {
                validate: (value) =>
                  value === getValues("password") || "Passwords do not match",
              })}
              error={!!errors.confirmPassword}
              helperText={errors.confirmPassword?.message}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <LockIcon fontSize="small" color="action" />
                  </InputAdornment>
                ),
              }}
            />

            <Button
              type="submit"
              fullWidth
              variant="contained"
              size="large"
              disabled={!!tokenError || isSubmitting}
              sx={{
                mt: 4,
                mb: 2,
                py: 1.5,
                fontWeight: 600,
                borderRadius: 2,
                textTransform: "none",
                fontSize: "1rem",
              }}
            >
              {isSubmitting ? (
                <CircularProgress size={24} color="inherit" />
              ) : (
                "Create Account"
              )}
            </Button>
          </Box>

          {/* Navigation Footer */}
          <Box sx={{ textAlign: "center", mt: 2 }}>
            <Typography variant="body2" color="text.secondary">
              Already have an account?{" "}
              <Button
                onClick={() => navigate("/login")}
                sx={{
                  p: 0,
                  minWidth: "auto",
                  textTransform: "none",
                  fontWeight: 600,
                  verticalAlign: "baseline",
                }}
              >
                Sign in
              </Button>
            </Typography>
          </Box>
        </CardContent>
      </Card>
    </Box>
  );
};

export default Register;
